export type AuthStackParamList = {
  Splash: undefined;
  LocationPermission: { initialTab?: 'auto' | 'manual' } | undefined;
  LocationSelection: undefined;
  LocationNotFound: undefined;
  Login: undefined;
  Signup: undefined;
  Otp: { phoneNumber: string; devOtp?: string };
  CreateAccount: { phoneNumber: string; verifiedPhoneToken: string };
  Home: undefined;
  Category: undefined;
  CategoryDetail: { categoryId: string; subcategoryId?: string };
  Search: undefined;
  ProductDetail: { productId?: string } | undefined;
  Cart: undefined;
  Address: undefined;
  AddressForm: { mode: 'add' } | { mode: 'edit'; addressId: string };
  DeliveryOptions: undefined;
  Payment: undefined;
  ReviewOrder: undefined;
  Processing: undefined;
  PaymentFailed: { message?: string } | undefined;
  PaymentSuccess: undefined;
  OrderConfirmation: { orderId: string };
  OrderTracking: { orderId?: string; variant?: 'onTime' | 'delayed' } | undefined;
  OrderIssue: undefined;
  OrderDetails: { orderId: string };
  OrderHistory: undefined;
  Reorder: { orderId: string };
  CancelOrder: { orderId: string };
  CancelIneligible: undefined;
  OrderCancelled: { orderId?: string } | undefined;
  RefundStatus: undefined;
  RefundDelayed: undefined;
  RefundCompleted: undefined;
  SupportHome: undefined;
  ReportIssue: undefined;
  IssueDetails: { issueType: string } | undefined;
  IssueSubmitted: undefined;
  IssueResolution: undefined;
  IssueResolved: undefined;
  Profile: undefined;
  EditProfile: undefined;
  ProfileAddresses: undefined;
  ProfilePayments: undefined;
  SavedItems: undefined;
  Notifications: undefined;
  NotificationDetail: { notificationId: string };
  Settings: undefined;
  StoreDetail: { storeId?: string; storeName?: string } | undefined;
};
