export type AuthStackParamList = {
  Splash: undefined;
  LocationPermission: { initialTab?: 'auto' | 'manual' } | undefined;
  LocationSelection: undefined;
  LocationNotFound: undefined;
  Login: undefined;
  Signup: undefined;
  Otp: { phoneNumber: string; devOtp?: string };
  CreateAccount: { phoneNumber: string; verifiedPhoneToken: string };
  Home: undefined;
  Category: undefined;
  CategoryDetail: { categoryId: string; subcategoryId?: string };
  Search: undefined;
  ProductDetail: { productId?: string } | undefined;
  Cart: undefined;
  Address: undefined;
  AddressForm: { mode: 'add' } | { mode: 'edit'; addressId: string };
  DeliveryOptions: undefined;
  Payment: undefined;
  ReviewOrder: undefined;
  Processing: undefined;
  PaymentFailed: { message?: string } | undefined;
  OrderConfirmation: { orderId: string };
  OrderTracking: { orderId?: string } | undefined;
  OrderDetails: { orderId: string; openRate?: boolean };
  OrderHistory: undefined;
  Reorder: { orderId: string };
  CancelOrder: { orderId: string };
  CancelIneligible: { orderId: string };
  OrderCancelled: { orderId: string };
  SupportHome: undefined;
  ReportIssue: undefined;
  IssueDetails: { issueType: string; orderId: string; orderNumber: string };
  Profile: undefined;
  EditProfile: undefined;
  ProfileAddresses: undefined;
  ProfilePayments: undefined;
  SavedItems: undefined;
  Notifications: undefined;
  NotificationDetail: { notificationId: string };
  Settings: undefined;
  StoreDetail: { categoryId: string; categoryName?: string };
};
